import './firebase-web.js';
const form=document.querySelector('[data-form="exam"]'),list=document.querySelector('[data-list="exam"]'),modal=document.getElementById('examModal'),editForm=document.getElementById('examEditForm');let cache=[];
const fdate=v=>!v?'Sem data':(v.toDate?v.toDate():new Date(v)).toLocaleDateString('pt-BR');const inputDate=v=>!v?'':(v.toDate?v.toDate():new Date(v)).toISOString().slice(0,10);const num=v=>v===''?'':Number(String(v).replace(',','.'));
function open(e){editForm.id.value=e.id;editForm.category.value=e.categoria||'';editForm.title.value=e.titulo||'';editForm.date.value=inputDate(e.data);editForm.week.value=e.semana||'';editForm.place.value=e.local||'';editForm.pesoFetal.value=e.pesoFetal||'';editForm.percentil.value=e.percentil||'';editForm.comprimentoFetal.value=e.comprimentoFetal||'';editForm.arquivoUrl.value=e.arquivoUrl||'';editForm.notes.value=e.observacoes||'';modal.hidden=false;document.body.classList.add('modal-open')}
function close(){modal.hidden=true;document.body.classList.remove('modal-open')}
async function load(){const {db,collection,getDocs,query,orderBy}=IUNA_FIREBASE;const snap=await getDocs(query(collection(db,'iuna_exames'),orderBy('data','desc')));cache=snap.docs.map(d=>({id:d.id,...d.data()}));list.innerHTML=cache.length?cache.map(e=>`<article class="mini-card"><small>${e.categoria||'Exame'}</small><strong>${e.titulo||'Sem título'}</strong><p>📅 ${fdate(e.data)} • 🤰 ${e.semana||'sem semana'}</p><p>🏥 ${e.local||'Local não informado'}</p>${e.pesoFetal?`<p>👶 ${e.pesoFetal}g • Percentil ${e.percentil||'—'}</p>`:''}${e.arquivoUrl?`<a class="secondary-btn" href="${e.arquivoUrl}" target="_blank">Visualizar arquivo</a>`:''}<div class="button-row"><button class="secondary-btn" data-edit-exam="${e.id}">Editar</button></div></article>`).join(''):'<article class="mini-card"><strong>Nenhum exame cadastrado.</strong></article>'}
form?.addEventListener('submit',async ev=>{ev.preventDefault();const {db,collection,addDoc,Timestamp,serverTimestamp}=IUNA_FIREBASE;const fd=new FormData(form),date=fd.get('date');await addDoc(collection(db,'iuna_exames'),{categoria:fd.get('category'),titulo:fd.get('title'),data:date?Timestamp.fromDate(new Date(`${date}T12:00:00`)):null,semana:fd.get('week')||'',local:fd.get('place')||'',pesoFetal:num(fd.get('pesoFetal')),percentil:num(fd.get('percentil')),comprimentoFetal:num(fd.get('comprimentoFetal')),arquivoUrl:fd.get('arquivoUrl')||'',observacoes:fd.get('notes')||'',status:'realizado',createdAt:serverTimestamp()});form.reset();await load();alert('Exame salvo 💜')});
list?.addEventListener('click',ev=>{const b=ev.target.closest('[data-edit-exam]');if(b){const e=cache.find(x=>x.id===b.dataset.editExam);if(e)open(e)}});document.addEventListener('click',async ev=>{if(ev.target.matches('[data-close-exam-modal]')||ev.target===modal)close();if(ev.target.matches('[data-delete-exam]')){const id=editForm.id.value;if(confirm('Excluir exame?')){const {db,doc,deleteDoc}=IUNA_FIREBASE;await deleteDoc(doc(db,'iuna_exames',id));close();load()}}});
editForm?.addEventListener('submit',async ev=>{ev.preventDefault();const {db,doc,updateDoc,Timestamp}=IUNA_FIREBASE;const fd=new FormData(editForm),date=fd.get('date');await updateDoc(doc(db,'iuna_exames',fd.get('id')),{categoria:fd.get('category'),titulo:fd.get('title'),data:date?Timestamp.fromDate(new Date(`${date}T12:00:00`)):null,semana:fd.get('week')||'',local:fd.get('place')||'',pesoFetal:num(fd.get('pesoFetal')),percentil:num(fd.get('percentil')),comprimentoFetal:num(fd.get('comprimentoFetal')),arquivoUrl:fd.get('arquivoUrl')||'',observacoes:fd.get('notes')||'',updatedAt:new Date()});close();await load();alert('Exame atualizado')});load();
