import './firebase-web.js';
const form=document.querySelector('[data-form="photo"]'),list=document.querySelector('[data-list="photo"]'),modal=document.getElementById('photoModal'),edit=document.getElementById('photoEditForm');let cache=[];
const categoryMap={'Barriga':'barriga','Ultrassom':'ultrassons','Família':'familia','Enxoval':'enxoval','Consultas':'consultas','Chá de bebê':'cha-bebe','Outros':'outros'};
function path(p){return `./public/img/galeria/${categoryMap[p.categoria]||'outros'}/${p.arquivo||p.fileName||''}`}
const fdate=v=>!v?'Sem data':(v.toDate?v.toDate():new Date(v)).toLocaleDateString('pt-BR');const inputDate=v=>!v?'':(v.toDate?v.toDate():new Date(v)).toISOString().slice(0,10);
function render(){const q=(document.getElementById('gallerySearch')?.value||'').toLowerCase();const cat=document.getElementById('galleryCategoryFilter')?.value||'Todas';let rows=cache.filter(p=>(cat==='Todas'||p.categoria===cat)&&JSON.stringify(p).toLowerCase().includes(q));list.innerHTML=rows.length?rows.map(p=>`<article class="photo-card"><img src="${path(p)}" onerror="this.src='./public/icons/icon.svg'"><div class="photo-card-body"><div class="tag-row"><span class="tag">${p.categoria}</span><span class="tag">${p.semana||'sem semana'}</span></div><h3>${p.titulo||'Memória da Iúna'}</h3><p>${p.legenda||''}</p><p>📅 ${fdate(p.data)}</p><button class="secondary-btn" data-open-photo="${p.id}">Visualizar / editar</button></div></article>`).join(''):'<article class="mini-card"><strong>Nenhuma foto cadastrada.</strong></article>'}
async function load(){const {db,collection,getDocs,query,orderBy}=IUNA_FIREBASE;const snap=await getDocs(query(collection(db,'iuna_galeria'),orderBy('data','desc')));cache=snap.docs.map(d=>({id:d.id,...d.data()}));render()}
form?.addEventListener('submit',async ev=>{ev.preventDefault();const {db,collection,addDoc,Timestamp,serverTimestamp}=IUNA_FIREBASE;const fd=new FormData(form),date=fd.get('date');await addDoc(collection(db,'iuna_galeria'),{categoria:fd.get('category'),arquivo:fd.get('fileName'),titulo:fd.get('title')||'Memória da Iúna',semana:fd.get('week')||'',data:date?Timestamp.fromDate(new Date(`${date}T12:00:00`)):null,legenda:fd.get('caption')||'',createdAt:serverTimestamp()});form.reset();await load();alert('Foto cadastrada 💜')});
function open(p){document.getElementById('modalPhotoImage').src=path(p);document.getElementById('modalPhotoTitle').textContent=p.titulo||'Memória';document.getElementById('modalPhotoCaption').textContent=p.legenda||'';edit.id.value=p.id;edit.category.value=p.categoria||'';edit.fileName.value=p.arquivo||'';edit.title.value=p.titulo||'';edit.week.value=p.semana||'';edit.date.value=inputDate(p.data);edit.caption.value=p.legenda||'';modal.hidden=false;document.body.classList.add('modal-open')}
list?.addEventListener('click',ev=>{const b=ev.target.closest('[data-open-photo]');if(b){const p=cache.find(x=>x.id===b.dataset.openPhoto);if(p)open(p)}});document.addEventListener('input',ev=>{if(ev.target.id==='gallerySearch'||ev.target.id==='galleryCategoryFilter')render()});document.addEventListener('click',async ev=>{if(ev.target.matches('[data-close-photo-modal]')||ev.target===modal){modal.hidden=true;document.body.classList.remove('modal-open')}if(ev.target.matches('[data-delete-photo]')){if(confirm('Excluir registro da foto?')){const {db,doc,deleteDoc}=IUNA_FIREBASE;await deleteDoc(doc(db,'iuna_galeria',edit.id.value));modal.hidden=true;await load()}}});edit?.addEventListener('submit',async ev=>{ev.preventDefault();const {db,doc,updateDoc,Timestamp}=IUNA_FIREBASE;const fd=new FormData(edit),date=fd.get('date');await updateDoc(doc(db,'iuna_galeria',fd.get('id')),{categoria:fd.get('category'),arquivo:fd.get('fileName'),titulo:fd.get('title'),semana:fd.get('week'),data:date?Timestamp.fromDate(new Date(`${date}T12:00:00`)):null,legenda:fd.get('caption'),updatedAt:new Date()});modal.hidden=true;document.body.classList.remove('modal-open');await load()});load().catch(console.error);
